export interface Game {
  id: string;
  title: string;
  genre: string;
  description: string;
  image: string;
  rating: number;
  ageGroup: string;
}

export const games: Game[] = [
  {
    id: "1",
    title: "Beat Saber",
    genre: "Ритм",
    description: "Режьте кубики под музыку",
    image: "/images/Beat Saber.webp",
    rating: 9.5,
    ageGroup: "Для детей",
  },
  {
    id: "2",
    title: "Resident Evil 4 VR",
    genre: "Хоррор",
    description: "Классика хоррора в полном VR",
    image: "/images/Resident Evil 4 VR.webp",
    rating: 9.3,
    ageGroup: "Для взрослых",
  },
  {
    id: "3",
    title: "Batman: Arkham Shadow",
    genre: "Экшн",
    description: "Станьте Бэтменом в полнометражном приключении",
    image: "/images/Batman Arkham Shadow.webp",
    rating: 9.4,
    ageGroup: "Для взрослых",
  },
  {
    id: "4",
    title: "Pistol Whip",
    genre: "Ритм-экшн",
    description: "Стреляйте под музыку в стиле нуар",
    image: "/images/Pistol Whip.webp",
    rating: 9.2,
    ageGroup: "Для взрослых",
  },
  {
    id: "5",
    title: "The Walking Dead: Saints & Sinners",
    genre: "Хоррор-выживание",
    description: "Выживайте в Новом Орлеане среди зомби",
    image: "/images/The Walking Dead Saints & Sinners.webp",
    rating: 9.1,
    ageGroup: "Для взрослых",
  },
  {
    id: "6",
    title: "Marvel's Deadpool VR",
    genre: "Экшн",
    description: "Станьте Мерси Килом в VR-приключении",
    image: "/images/Marvel's Deadpool VR.webp",
    rating: 8.8,
    ageGroup: "Для взрослых",
  },
  {
    id: "7",
    title: "Metro Awakening",
    genre: "Хоррор-шутер",
    description: "Погрузитесь в мрачный мир метро",
    image: "/images/Metro Awakening.webp",
    rating: 8.9,
    ageGroup: "Для взрослых",
  },
  {
    id: "8",
    title: "I Am Cat",
    genre: "Приключение",
    description: "Будьте котом в VR",
    image: "/images/I Am Cat.webp",
    rating: 8.5,
    ageGroup: "Для детей",
  },
  {
    id: "9",
    title: "Gorilla Tag",
    genre: "Мультиплеер",
    description: "Бесплатно, весело, затягивает",
    image: "/images/Gorrilatag.webp",
    rating: 9.0,
    ageGroup: "Для детей",
  },
  {
    id: "10",
    title: "Blade & Sorcery: Nomad",
    genre: "Экшн",
    description: "Средневековый бой с реальной физикой",
    image: "/images/Blade & Sorcery Nomad.webp",
    rating: 8.8,
    ageGroup: "Для взрослых",
  },
  {
    id: "11",
    title: "GORN",
    genre: "Экшн",
    description: "Кровавые гладиаторские бои",
    image: "/images/GORN.webp",
    rating: 8.5,
    ageGroup: "Для взрослых",
  },
  {
    id: "12",
    title: "Into the Radius",
    genre: "Выживание",
    description: "Исследуйте аномальную зону",
    image: "/images/Into the Radius.webp",
    rating: 8.7,
    ageGroup: "Для взрослых",
  },
  {
    id: "13",
    title: "The Climb 2",
    genre: "Спорт",
    description: "Корпоративное альпинизм в VR",
    image: "/images/The Climb 2.webp",
    rating: 8.3,
    ageGroup: "Для детей",
  },
  {
    id: "14",
    title: "Job Simulator",
    genre: "Комедия",
    description: "Работайте где угодно, ломайте всё",
    image: "/images/Job Simulator.webp",
    rating: 8.2,
    ageGroup: "Для детей",
  },
  {
    id: "15",
    title: "Eleven Table Tennis",
    genre: "Спорт",
    description: "Настольный теннис с реальной физикой",
    image: "/images/Eleven Table Tennis.webp",
    rating: 9.0,
    ageGroup: "Для детей",
  },
  {
    id: "16",
    title: "Stranger Things VR",
    genre: "Хоррор",
    description: "Погрузитесь в мир Старрейндж Тингс",
    image: "/images/Stranger Things VR.webp",
    rating: 7.8,
    ageGroup: "Для взрослых",
  },
  {
    id: "17",
    title: "Contractors Showdown: ExfilZone",
    genre: "Тактический шутер",
    description: "Тактические бои с эвакуацией",
    image: "/images/Contractors Showdown ExfilZone.webp",
    rating: 9.0,
    ageGroup: "Для взрослых",
  },
  {
    id: "18",
    title: "Starship Troopers: Continuum",
    genre: "Шутер",
    description: "Сражайтесь с жуками из фильма",
    image: "/images/Starship Troopers Continuum.webp",
    rating: 7.5,
    ageGroup: "Для взрослых",
  },
  {
    id: "19",
    title: "UNDERDOGS",
    genre: "Экшн",
    description: "Механические бои в подпольном турнире",
    image: "/images/UNDERDOGS.webp",
    rating: 8.4,
    ageGroup: "Для взрослых",
  },
  {
    id: "20",
    title: "Alien: Rogue Incursion",
    genre: "Хоррор",
    description: "Выживайте среди ксеноморфов",
    image: "/images/Alien Rogue Incursion.webp",
    rating: 8.1,
    ageGroup: "Для взрослых",
  },
  {
    id: "21",
    title: "Zero Caliber 2",
    genre: "Шутер",
    description: "Военный шутер с друзьями",
    image: "/images/Zero Caliber 2.webp",
    rating: 8.6,
    ageGroup: "Для взрослых",
  },
  {
    id: "22",
    title: "MADiSON VR",
    genre: "Хоррор",
    description: "Вызывайте демонов через фотоаппарат",
    image: "/images/MADiSON VR.webp",
    rating: 8.3,
    ageGroup: "Для взрослых",
  },
  {
    id: "23",
    title: "Call of the Sea",
    genre: "Приключение",
    description: "Загадочный остров в Тихом океане",
    image: "/images/Call of the Sea.webp",
    rating: 8.0,
    ageGroup: "Для детей",
  },
  {
    id: "24",
    title: "Chernobyl Again",
    genre: "Приключение",
    description: "Временные петли в зоне ЧАЭС",
    image: "/images/Chernobyl Again.webp",
    rating: 8.2,
    ageGroup: "Для взрослых",
  },
  {
    id: "25",
    title: "AFFECTED: The Manor",
    genre: "Хоррор",
    description: "Пугающее исследование заброшенного особняка",
    image: "/images/AFFECTED The Manor – Complete Edition.webp",
    rating: 7.5,
    ageGroup: "Для взрослых",
  },
  {
    id: "26",
    title: "Agent Simulator",
    genre: "Шутер",
    description: "Будьте секретным агентом",
    image: "/images/Agent Simulator.webp",
    rating: 7.0,
    ageGroup: "Для детей",
  },
  {
    id: "27",
    title: "Animal Rivals",
    genre: "Партия",
    description: "Забавные бои животных друг с другом",
    image: "/images/Animal Rivals.webp",
    rating: 7.2,
    ageGroup: "Для детей",
  },
  {
    id: "28",
    title: "Another Door - Escape Room",
    genre: "Головоломка",
    description: "Решайте загадки и выбирайтесь из комнат",
    image: "/images/Another Door – Escape Room.webp",
    rating: 7.4,
    ageGroup: "Для детей",
  },
  {
    id: "29",
    title: "BIG SHOTS",
    genre: "Экшн",
    description: "Уничтожайте врагов в мега-мехах",
    image: "/images/BIG SHOTS.webp",
    rating: 7.6,
    ageGroup: "Для детей",
  },
  {
    id: "30",
    title: "Border Bots VR",
    genre: "Пазл-экшн",
    description: "Проверяйте роботов на пропускной",
    image: "/images/Border Bots VR.webp",
    rating: 7.8,
    ageGroup: "Для детей",
  },
  {
    id: "31",
    title: "Breathedge: Cosmic Cluck",
    genre: "Приключение",
    description: "Космическое приключение с курицей",
    image: "/images/Breathedge Cosmic Cluck.webp",
    rating: 6.5,
    ageGroup: "Для детей",
  },
  {
    id: "32",
    title: "Creed: Rise to Glory",
    genre: "Спорт",
    description: "Боксёрские бои как в фильме Крид",
    image: "/images/Creed Rise to Glory – Championship Edition.webp",
    rating: 8.0,
    ageGroup: "Для детей",
  },
  {
    id: "33",
    title: "Crisis Brigade 2 Reloaded",
    genre: "Шутер",
    description: "Аркадный шутер с ограблениями",
    image: "/images/Crisis Brigade 2 Reloaded.webp",
    rating: 7.5,
    ageGroup: "Для детей",
  },
  {
    id: "34",
    title: "Drop Dead: The Cabin",
    genre: "Хоррор-шутер",
    description: "Выживайте в хижине среди зомби",
    image: "/images/Drop Dead The Cabin.webp",
    rating: 7.8,
    ageGroup: "Для взрослых",
  },
  {
    id: "35",
    title: "Elven Assassin",
    genre: "Экшн",
    description: "Стреляйте из лука по оркам",
    image: "/images/Elven Assassin.webp",
    rating: 7.7,
    ageGroup: "Для детей",
  },
  {
    id: "36",
    title: "Epic Roller Coasters",
    genre: "Аттракцион",
    description: "Безумные американские горки в VR",
    image: "/images/Epic Roller Coasters.webp",
    rating: 7.0,
    ageGroup: "Для детей",
  },
  {
    id: "37",
    title: "Escape Simulator",
    genre: "Головоломка",
    description: "Кооперативные квесты на побег",
    image: "/images/Escape Simulator.webp",
    rating: 8.2,
    ageGroup: "Для детей",
  },
  {
    id: "38",
    title: "EXOcars",
    genre: "Гонки",
    description: "Аркадные гонки на экзоскелетах",
    image: "/images/EXOcars.webp",
    rating: 7.3,
    ageGroup: "Для детей",
  },
  {
    id: "39",
    title: "Eye of the Temple",
    genre: "Приключение",
    description: "Исследуйте храм шагающими платформами",
    image: "/images/Eye of the Temple.webp",
    rating: 7.9,
    ageGroup: "Для детей",
  },
  {
    id: "40",
    title: "FNAF: Help Wanted 2",
    genre: "Хоррор",
    description: "Пятая ночь в пиццерии на стажировке",
    image: "/images/Five Nights at Freddy's Help Wanted 2.webp",
    rating: 8.4,
    ageGroup: "Для взрослых",
  },
  {
    id: "41",
    title: "Fracked",
    genre: "Шутер",
    description: "Шутер от первого лица с гонками",
    image: "/images/Fracked.webp",
    rating: 7.6,
    ageGroup: "Для взрослых",
  },
  {
    id: "42",
    title: "Galaxy Kart",
    genre: "Гонки",
    description: "Космические гонки в стиле Mario Kart",
    image: "/images/Galaxy Kart.webp",
    rating: 7.4,
    ageGroup: "Для детей",
  },
  {
    id: "43",
    title: "Gun Club VR",
    genre: "Симулятор",
    description: "Стрелковый тир с реалистичным оружием",
    image: "/images/Gun Club VR.webp",
    rating: 8.0,
    ageGroup: "Для взрослых",
  },
  {
    id: "44",
    title: "Hand Physics Lab",
    genre: "Песочница",
    description: "Играйте руками с физическими объектами",
    image: "/images/Hand Physics Lab.webp",
    rating: 7.5,
    ageGroup: "Для детей",
  },
  {
    id: "45",
    title: "HandBoi",
    genre: "Аркада",
    description: "Забавная игра с руками",
    image: "/images/HandBoi.webp",
    rating: 6.8,
    ageGroup: "Для детей",
  },
  {
    id: "46",
    title: "Hide The Corpse",
    genre: "Пазл",
    description: "Прячьте тело от полиции",
    image: "/images/Hide The Corpse.webp",
    rating: 7.2,
    ageGroup: "Для детей",
  },
  {
    id: "47",
    title: "Human Fall Flat VR",
    genre: "Головоломка",
    description: "Физическая головоломка с падающими человечками",
    image: "/images/Human Fall Flat VR.webp",
    rating: 8.3,
    ageGroup: "Для детей",
  },
  {
    id: "48",
    title: "HUMANITY",
    genre: "Пазл",
    description: "Ведите толпы людей к спасению",
    image: "/images/HUMANITY.webp",
    rating: 8.5,
    ageGroup: "Для детей",
  },
  {
    id: "49",
    title: "I Am Security",
    genre: "Симулятор",
    description: "Работайте охранником в аэропорту",
    image: "/images/I Am Security.webp",
    rating: 7.0,
    ageGroup: "Для детей",
  },
  {
    id: "50",
    title: "Into Black",
    genre: "Шутер",
    description: "Кооперативный шутер в космосе",
    image: "/images/Into Black.webp",
    rating: 7.8,
    ageGroup: "Для взрослых",
  },
  {
    id: "51",
    title: "Iron Rebellion",
    genre: "Мех-шутер",
    description: "Управляйте боевымиMech'ами",
    image: "/images/Iron Rebellion.webp",
    rating: 7.9,
    ageGroup: "Для взрослых",
  },
  {
    id: "52",
    title: "Journey Of The Gods",
    genre: "Приключение",
    description: "Эпическое приключение в мире богов",
    image: "/images/Journey Of The Gods.webp",
    rating: 7.7,
    ageGroup: "Для детей",
  },
  {
    id: "53",
    title: "LEGO Bricktales",
    genre: "Головоломка",
    description: "Стройте из LEGO в красивых мирах",
    image: "/images/LEGO Bricktales.webp",
    rating: 8.0,
    ageGroup: "Для детей",
  },
  {
    id: "54",
    title: "LES MILLS BODYCOMBAT",
    genre: "Фитнес",
    description: "Боевые искусства для тренировок",
    image: "/images/LES MILLS BODYCOMBAT.webp",
    rating: 8.2,
    ageGroup: "Для детей",
  },
  {
    id: "55",
    title: "Medal of Honor: Above and Beyond",
    genre: "Шутер",
    description: "Военные миссии Второй мировой",
    image: "/images/Medal of Honor Above and Beyond.webp",
    rating: 7.8,
    ageGroup: "Для взрослых",
  },
  {
    id: "56",
    title: "Metal: Hellsinger VR",
    genre: "Ритм-шутер",
    description: "Стреляйте под тяжёлую музыку",
    image: "/images/Metal Hellsinger VR.webp",
    rating: 8.3,
    ageGroup: "Для взрослых",
  },
  {
    id: "57",
    title: "Moorhuhn VR Blast",
    genre: "Аркада",
    description: "Охота на цыплят в VR",
    image: "/images/Moorhuhn VR Blast.webp",
    rating: 6.5,
    ageGroup: "Для детей",
  },
  {
    id: "58",
    title: "Moss: Book II",
    genre: "Приключение",
    description: "Продолжение истории мышки-рыцаря",
    image: "/images/Moss Book II.webp",
    rating: 8.8,
    ageGroup: "Для детей",
  },
  {
    id: "59",
    title: "MudRunner VR",
    genre: "Симулятор",
    description: "Преодолевайте грязь на внедорожниках",
    image: "/images/MudRunner VR.webp",
    rating: 7.5,
    ageGroup: "Для детей",
  },
  {
    id: "60",
    title: "On Point",
    genre: "Шутер",
    description: "Тактический шутер на выживание",
    image: "/images/On Point.webp",
    rating: 7.3,
    ageGroup: "Для взрослых",
  },
  {
    id: "61",
    title: "Outta Hand",
    genre: "Экшн",
    description: "Летайте и сражайтесь руками",
    image: "/images/Outta Hand.webp",
    rating: 7.0,
    ageGroup: "Для детей",
  },
  {
    id: "62",
    title: "Paint The Town Red VR",
    genre: "Экшн",
    description: "Воксельные драки в разных эпохах",
    image: "/images/Paint The Town Red VR.webp",
    rating: 7.8,
    ageGroup: "Для детей",
  },
  {
    id: "63",
    title: "Paranormal Activity: The Lost Soul",
    genre: "Хоррор",
    description: "Исследуйте дом с паранормальной активностью",
    image: "/images/Paranormal Activity The Lost Soul.webp",
    rating: 7.6,
    ageGroup: "Для взрослых",
  },
  {
    id: "64",
    title: "Path of the Warrior",
    genre: "Боевик",
    description: "Уличные драки в стиле 90-х",
    image: "/images/Path of the Warrior.webp",
    rating: 7.5,
    ageGroup: "Для взрослых",
  },
  {
    id: "65",
    title: "Pixel Ripped 1978",
    genre: "Ностальгия",
    description: "Играйте в ретро-игры в ретро-стиле",
    image: "/images/Pixel Ripped 1978.webp",
    rating: 7.2,
    ageGroup: "Для детей",
  },
  {
    id: "66",
    title: "Propagation: Paradise Hotel",
    genre: "Хоррор",
    description: "Выживайте в зомби-отеле",
    image: "/images/Propagation Paradise Hotel.webp",
    rating: 7.4,
    ageGroup: "Для взрослых",
  },
  {
    id: "67",
    title: "Ragnarock",
    genre: "Ритм",
    description: "Бейте в баулы под викинг-метал",
    image: "/images/Ragnarock.webp",
    rating: 8.0,
    ageGroup: "Для детей",
  },
  {
    id: "68",
    title: "Riven",
    genre: "Головоломка",
    description: "Классическая головоломка в перезапуске",
    image: "/images/Riven.webp",
    rating: 8.1,
    ageGroup: "Для детей",
  },
  {
    id: "69",
    title: "SKYBOX",
    genre: "Медиаплеер",
    description: "Просмотр видео и фильмов в VR",
    image: "/images/SKYBOX.webp",
    rating: 8.5,
    ageGroup: "Для детей",
  },
  {
    id: "70",
    title: "Space Pirate Trainer DX",
    genre: "Шутер",
    description: "Аркадный шутер в космосе",
    image: "/images/Space Pirate Trainer DX.webp",
    rating: 8.2,
    ageGroup: "Для детей",
  },
  {
    id: "71",
    title: "Spatial Zombies Pro",
    genre: "Хоррор-шутер",
    description: "Зомби в смешанной реальности",
    image: "/images/Spatial Zombies Pro – Mixed Reality.webp",
    rating: 7.0,
    ageGroup: "Для взрослых",
  },
  {
    id: "72",
    title: "Stilt",
    genre: "Приключение",
    description: "Ходите на ходулях по миру",
    image: "/images/Stilt.webp",
    rating: 7.3,
    ageGroup: "Для детей",
  },
  {
    id: "73",
    title: "Sugar Mess",
    genre: "Аркада",
    description: "Сладкий хаос в стиле детской книжки",
    image: "/images/Sugar Mess – Let's Play Jolly Battle.webp",
    rating: 6.8,
    ageGroup: "Для детей",
  },
  {
    id: "74",
    title: "The Burst",
    genre: "Экшн",
    description: "Киберпанковые бои на мечах",
    image: "/images/The Burst.webp",
    rating: 7.7,
    ageGroup: "Для взрослых",
  },
  {
    id: "75",
    title: "The Exorcist: Legion VR",
    genre: "Хоррор",
    description: "Изгоняйте демонов в пяти главах",
    image: "/images/The Exorcist Legion VR.webp",
    rating: 8.0,
    ageGroup: "Для взрослых",
  },
  {
    id: "76",
    title: "The Lab",
    genre: "Демо",
    description: "Коллекция VR-опытов от Valve",
    image: "/images/The Lab.webp",
    rating: 8.5,
    ageGroup: "Для детей",
  },
  {
    id: "77",
    title: "The Light Brigade",
    genre: "Рогалик",
    description: "Тактический шутер с тёмными тайнами",
    image: "/images/The Light Brigade.webp",
    rating: 8.6,
    ageGroup: "Для взрослых",
  },
  {
    id: "78",
    title: "Underworld Overseer",
    genre: "Стратегия",
    description: "Управляйте подземельем как злодей",
    image: "/images/Underworld Overseer.webp",
    rating: 7.5,
    ageGroup: "Для детей",
  },
  {
    id: "79",
    title: "Vermillion - VR Painting",
    genre: "Творчество",
    description: "Рисуйте маслом в VR",
    image: "/images/Vermillion – VR Painting.webp",
    rating: 8.0,
    ageGroup: "Для детей",
  },
  {
    id: "80",
    title: "Waltz of the Wizard",
    genre: "Песочница",
    description: "Колдуйте в башне волшебника",
    image: "/images/Waltz of the Wizard.webp",
    rating: 8.3,
    ageGroup: "Для детей",
  },
  {
    id: "81",
    title: "Wander",
    genre: "Исследование",
    description: "Путешествуйте по миру в VR",
    image: "/images/Wander.webp",
    rating: 7.8,
    ageGroup: "Для детей",
  },
  {
    id: "82",
    title: "Max Mustard",
    genre: "Приключение",
    description: "Платформер с милыми персонажами",
    image: "/images/Max Mustard.webp",
    rating: 8.1,
    ageGroup: "Для детей",
  },
];

export const TOTAL_GAMES = games.length;
